blog/urls.py
from django.urls import path, re_path

from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    re_path(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    re_path(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    re_path(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tags'),
    path('index', views.IndexView.as_view(), name='index'),
    path('about', views.about, name='about'),
    path('projects', views.ProjIndexView.as_view(), name='projects'),
    re_path(r'^project/(?P<pk>[0-9]+)/$', views.ProjDetailView.as_view(), name='proj_detail'),
]

comments/urls.py
from django.urls import re_path

from . import views

app_name = 'comments'
urlpatterns = [
    re_path(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    # re_path(r'^search/', include('haystack.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

# Create your models here.


def default_cat():
    return Category.objects.get_or_create(name='Default')[0].pk


class Category(models.Model):
    """
    post category
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    post tag
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    posts
    """
    title = models.CharField(max_length=120)
    excerpt = models.CharField(max_length=1000, blank=True)
    body = models.TextField()

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    category = models.ForeignKey(Category, default=default_cat, on_delete=models.SET_DEFAULT)
    tags = models.ManyToManyField(Tag, blank=True)

    # author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'mdx_math'
            ],
                extension_configs={
                    'mdx_math': {'enable_dollar_delimiter': True}
                }
            )
            self.excerpt = strip_tags(md.convert(self.body))[:100]
        super(Post, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def prev(self):
        try:
            pr = self.get_previous_by_created_time()
            return [pr]
        except self.DoesNotExist:
            return []

    def next(self):
        try:
            nx = self.get_next_by_created_time()
            return [nx]
        except self.DoesNotExist:
            return []


class Project(models.Model):
    name = models.CharField(max_length=120)
    created_time = models.DateField()
    skills = models.ManyToManyField(Tag)
    intro = models.TextField()
    body = models.TextField()
    link = models.CharField(max_length=200)
    image = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:proj_detail', kwargs={'pk': self.pk})

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Tag, Project
from comments.forms import CommentForm
import markdown
from django.views.generic import ListView, DetailView

# Create your views here.


def home(request):
    post_list = Post.objects.all().order_by('-created_time')[:3]
    proj_list = Project.objects.all().order_by('-created_time')[:4]
    return render(request, 'blog/home.html', context={
        'post_list': post_list,
        'proj_list': proj_list
    })


def about(request):
    return render(request, 'blog/about.html')


class IndexView(ListView):
    model = Post
    template_name = 'blog/blog.html'
    context_object_name = 'post_list'
    ordering = ['-created_time']
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['page_title'] = 'All Posts'
        return context


class ProjIndexView(ListView):
    model = Project
    template_name = 'blog/project_index.html'
    context_object_name = 'project_list'
    ordering = ['-created_time']
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['page_title'] = 'All Projects'
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        post = super().get_object()
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
            'mdx_math'
        ],
            extension_configs={
                'mdx_math': {'enable_dollar_delimiter': True}
            }
        )
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


class ProjDetailView(DetailView):
    model = Project
    template_name = 'blog/project_detail.html'
    context_object_name = 'proj'

    def get_object(self, queryset=None):
        proj = super().get_object()
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
            'mdx_math'
        ],
            extension_configs={
                'mdx_math': {'enable_dollar_delimiter': True}
            }
        )
        proj.body = md.convert(proj.body)
        return proj


def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month).order_by('-created_time')
    return render(request, 'blog/home.html', context={
        'post_list': post_list
    })


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(category=cate)

    def get_context_data(self, *, object_list=None, **kwargs):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        context = super(IndexView, self).get_context_data()
        context['page_title'] = cate.name
        return context


class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(tags=tag)

    def get_context_data(self, *, object_list=None, **kwargs):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        context = super(IndexView, self).get_context_data()
        context['page_title'] = tag.name
        return context

blog/templates/blog/about.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
<head>

   <!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>About Page</title>
	<meta name="description" content="">
	<meta name="author" content="">

   <!-- Mobile Specific Metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
    ================================================== -->
   <link rel="stylesheet" href="{% static 'blog/css/default.css' %}">
	<link rel="stylesheet" href="{% static 'blog/css/layout.css' %}">
   <link rel="stylesheet" href="{% static 'blog/css/media-queries.css' %}">

   <!-- Script
   ================================================== -->
	<script src="{% static 'blog/js/modernizr.js' %}"></script>

   <!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="{% static 'blog/images/favicon.ico' %}" >

</head>

<body>

   <!-- Header
   ================================================== -->
   <header>

      <div class="row">

         <div class="twelve columns">

            <div class="logo">
               <a href="{% url 'blog:home' %}"><img alt="" src="{% static 'blog/images/logo.png' %}"></a>
            </div>

            <nav id="nav-wrap">

               <a class="mobile-btn" href="#nav-wrap" title="Show navigation">Show navigation</a>
	            <a class="mobile-btn" href="#" title="Hide navigation">Hide navigation</a>

               <ul id="nav" class="nav">

	               <li><a href="{% url 'blog:home' %}">Home</a></li>
                   <li><a href="{% url 'blog:index' %}">Blogs</a></li>
                   <li><a href="{% url 'blog:projects' %}">Projects</a></li>
{#	               <li><span><a href="blog.html">Blog</a></span>#}
{#                     <ul>#}
{#                        <li><a href="blog.html">Blog Index</a></li>#}
{#                        <li><a href="single.html">Post</a></li>#}
{#                     </ul>#}
{#                  </li>#}
{#                  <li><span><a href="portfolio-index.html">Portfolio</a></span>#}
{#                     <ul>#}
{#                        <li><a href="portfolio-index.html">Portfolio Index</a></li>#}
{#                        <li><a href="portfolio.html">Portfolio Entry</a></li>#}
{#                     </ul>#}
{#                  </li>#}
	               <li class="current"><a href="{% url 'blog:about' %}">About</a></li>
                   <li><a href="{% static 'blog/images/teddy.pdf' %}">Resume</a></li>
{#                  <li><a href="contact.html">Contact</a></li>#}
{#                  <li><a href="styles.html">Features</a></li>#}

               </ul> <!-- end #nav -->

            </nav> <!-- end #nav-wrap -->

         </div>

      </div>

   </header> <!-- Header End -->

   <!-- Page Title
   ================================================== -->
   <div id="page-title">

      <div class="row">

         <div class="ten columns centered text-center">
            <h1>About Me</h1>

            <p>Current physics Ph.D student, interested in data science, looking for data scientist jobs.</p>
         </div>

      </div>

   </div> <!-- Page Title End-->

   <!-- Content
   ================================================== -->
   <div class="content-outer">

      <div id="page-content" class="row page">

         <div id="primary" class="eight columns">

            <section>

{#               <h1>Meet our talented team.</h1>#}
{##}
{#               <p class="lead">Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor,#}
{#               nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate#}
{#               cursus a sit amet mauris. Morbi accumsan ipsum velit. </p>#}

               <p>I grew up in China. I have been interested in mathematics and physics since I was a child.
                   After winning the first price in national math olympiad, I was admitted to Peking University.
               There, I spent one year at the College of Engineering, then changed major to physics.
               I started my graduate student era at Texas A&M Unversity from 2014.
               I work mainly on neutrino physics, fitting physics models to experimental data and predicting discovery limits for new experiments.
               You can find my works <a href="https://inspirehep.net/search?p=exactauthor%3AS.Liao.5&sf=earliestdate">here</a>.
               </p>
                <p>While I studied physics, I built up interests in computer technology and data science. I have been studying relevant topics such as Machine Learning since 2016. My background in physics data and statistics helped me quickly adapt to the concepts in data science.
                    I have also attended the OMSCS program at Georgia Tech from 2018 to further extend my knowel. </p>
                <p>I am actively looking for a data scientist position. Please contact me if you are interested. Here is my <a href="{% static 'blog/images/teddy.pdf' %}">resume</a>.</p>



            </section> <!-- section end -->

         </div> <!-- primary end -->

         <div id="secondary" class="four columns end">

            <aside id="sidebar">

               <div class="widget widget_search">
                  <h5>Search</h5>
                  <input class="text-search" type="text" name="q" required onfocus="if (this.value === 'Search here...') { this.value = ''; }" onblur="if(this.value === '') { this.value = 'Search here...'; }" value="Search here...">
                  <input type="submit" class="submit-search" value="">
                </form>
               </div>

{#               <div class="widget widget_text">#}
{#                  <h5 class="widget-title">Text Widget</h5>#}
{#                  <div class="textwidget">Proin gravida nibh vel velit auctor aliquet.#}
{#                  Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum,#}
{#                  nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus#}
{#                  a sit amet mauris. Morbi accumsan ipsum velit. </div>#}
{#		         </div>#}

               <div class="widget widget_contact">
{#					   <h5>Address and Phone</h5>#}
{#					   <p class="address">#}
{#						   Sparrow Studio<br>#}
{#						   1600 Amphitheatre Parkway <br>#}
{#						   Mountain View, CA 94043 US<br>#}
{#						   <span>(123) 456-7890</span>#}
{#					   </p>#}

					   <h5>Contact</h5>
					   <p>
                       E-mail: xionghang100@163.com<br>
                       Phone: (+86)18716354845<br>
{#                     Twitter: <a href="#">@sparrow</a><br>#}
{#                     Facebook: <a href="#">sparrow FB Page</a><br>#}
{#                     Google+: <a href="#">sparrow G+ Page</a>#}
                  </p>
				   </div>

{#               <div class="widget widget_photostream">#}
{#                  <h5>Photostream</h5>#}
{#                  <ul class="photostream cf">#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                  </ul>#}
{#	            </div>#}

            </aside>

         </div> <!-- secondary End-->

      </div> <!-- page-content End-->

   </div> <!-- Content End-->


 <!-- footer
   ================================================== -->
   <footer>

      <div class="row">

         <div class="twelve columns">

            <ul class="footer-nav">
					<li><a href="{% url 'blog:home' %}">Home</a></li>
              	<li><a href="{% url 'blog:index' %}">Blogs</a></li>
              	<li><a href="{% url 'blog:projects' %}">Projects</a></li>
              	<li><a href="{% url 'blog:about' %}">About</a></li>
{#              	<li><a href="#">Contact.</a></li>#}
{#               <li><a href="#">Features.</a></li>#}
			   </ul>

            <ul class="footer-social">
{#               <li><a href="#"><i class="fa fa-facebook"></i></a></li>#}
{#               <li><a href="#"><i class="fa fa-twitter"></i></a></li>#}
{#               <li><a href="#"><i class="fa fa-google-plus"></i></a></li>#}
               <li><a href="https://www.linkedin.com/in/%E8%88%AA-%E7%86%8A-9aa674156/"><i class="fa fa-linkedin"></i></a></li>
               <li><a href="https://www.facebook.com/hang.xiong.7758"><i class="fa fa-facebook"></i></a></li>
               <li><a href="https://www.instagram.com/teddy__xiong/"><i class="fa fa-instagram"></i></a></li>
               <li><a href="https://github.com/lifeNeedsCreation"><i class="fa fa-github"></i></a></li>
{#               <li><a href="#"><i class="fa fa-rss"></i></a></li>#}
            </ul>

            <ul class="copyright">
               <li>&copy; Teddy Xiong</li>
{#               <li>Design by <a href="http://www.styleshout.com/">Styleshout</a></li>               #}
            </ul>

         </div>

         <div id="go-top" style="display: block;"><a title="Back to Top" href="#">Go To Top</a></div>

      </div>

   </footer> <!-- Footer End-->

   <!-- Java Script
   ================================================== -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script>window.jQuery || document.write('<script src="js/jquery-1.10.2.min.js"><\/script>')</script>
   <script type="text/javascript" src="{% static 'blog/js/jquery-migrate-1.2.1.min.js' %}"></script>

   <script src="{% static 'blog/js/jquery.flexslider.js' %}"></script>
   <script src="{% static 'blog/js/doubletaptogo.js' %}"></script>
   <script src="{% static 'blog/js/init.js' %}"></script>

    {% block addtion_script %}
    {% endblock %}

</body>

</html>

blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
<head>

   <!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>Teddy's blog</title>
	<meta name="description" content="">
	<meta name="author" content="">

   <!-- Mobile Specific Metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
    ================================================== -->
   <link rel="stylesheet" href="{% static 'blog/css/default.css' %}">
	<link rel="stylesheet" href="{% static 'blog/css/layout.css' %}">
   <link rel="stylesheet" href="{% static 'blog/css/media-queries.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/colorful.css' %}">

   <!-- Script
   ================================================== -->
	<script src="{% static 'blog/js/modernizr.js' %}"></script>

   <!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="{% static 'blog/images/favicon.ico' %}" >

    <style>
        span.highlighted {
            color: red;
        }
    </style>

</head>

<body>

   <!-- Header
   ================================================== -->
   <header>

      <div class="row">

         <div class="twelve columns">

            <div class="logo">
               <a href="{% url 'blog:home' %}"><img alt="" src="{% static 'blog/images/logo.png' %}"></a>
            </div>

            <nav id="nav-wrap">

               <a class="mobile-btn" href="#nav-wrap" title="Show navigation">Show navigation</a>
	            <a class="mobile-btn" href="#" title="Hide navigation">Hide navigation</a>

               <ul id="nav" class="nav">

	               <li><a href="{% url 'blog:home' %}">Home</a></li>
                   <li class="current"><a href="{% url 'blog:index' %}">Blogs</a></li>
                   <li><a href="{% url 'blog:projects' %}">Projects</a></li>
{#	               <li><span><a href="blog.html">Blog</a></span>#}
{#                     <ul>#}
{#                        <li><a href="blog.html">Blog Index</a></li>#}
{#                        <li><a href="single.html">Post</a></li>#}
{#                     </ul>#}
{#                  </li>#}
{#                  <li><span><a href="portfolio-index.html">Portfolio</a></span>#}
{#                     <ul>#}
{#                        <li><a href="portfolio-index.html">Portfolio Index</a></li>#}
{#                        <li><a href="portfolio.html">Portfolio Entry</a></li>#}
{#                     </ul>#}
{#                  </li>#}
	               <li><a href="{% url 'blog:about' %}">About</a></li>
                   <li><a href="{% static 'blog/images/teddy.pdf' %}">Resume</a></li>
{#                  <li><a href="contact.html">Contact</a></li>#}
{#                  <li><a href="styles.html">Features</a></li>#}

               </ul> <!-- end #nav -->

            </nav> <!-- end #nav-wrap -->

         </div>

      </div>

   </header> <!-- Header End -->

   <!-- Page Title
   ================================================== -->
   <div id="page-title">

      <div class="row">

         <div class="ten columns centered text-center">
            {% block pagetitle %}

            {% endblock %}

{#            <p>Aenean condimentum, lacus sit amet luctus lobortis, dolores et quas molestias excepturi#}
{#            enim tellus ultrices elit, amet consequat enim elit noneas sit amet luctu. </p>#}
         </div>

      </div>

   </div> <!-- Page Title End-->

   <!-- Content
   ================================================== -->
   <div class="content-outer">

      <div id="page-content" class="row">

         {% block main %}
            {% endblock main %}

         <div id="secondary" class="four columns end">

            <aside id="sidebar">

               <div class="widget widget_search">
                  <h5>Search</h5>
                  <input class="text-search" type="text" name="q" required onfocus="if (this.value === 'Search here...') { this.value = ''; }" onblur="if(this.value === '') { this.value = 'Search here...'; }" value="Search here...">
                  <input type="submit" class="submit-search" value="">
                </form>
               </div>

            {% block toc %}
            {% endblock toc %}

               <div class="widget widget_categories">
                  <h5 class="widget-title">Recent Posts</h5>
                  <ul class="link-list cf">
                      {% get_recent_posts as posts %}
                      {% for pos in posts %}
                     <li><a href="{{ pos.get_absolute_url }}">{{ pos.title }}</a></li>
                      {% endfor %}
                  </ul>
		         </div>

               <div class="widget widget_categories">
                  <h5 class="widget-title">Categories</h5>
                  <ul class="link-list cf">
                      {% get_categories as cats %}
                      {% for cat in cats %}
                     <li><a href="{% url 'blog:category' cat.pk %}">{{ cat.name }} ({{ cat.post_set.count }})</a></li>
                      {% endfor %}
                  </ul>
               </div>

               <div class="widget widget_tag_cloud">
                  <h5 class="widget-title">Tags</h5>
                  <div class="tagcloud cf">
                      {% get_tags as tgs %}
                      {% for tg in tgs %}
                     <a href="{% url 'blog:tags' tg.pk %}">{{ tg.name }} ({{ tg.post_set.count }})</a>
                     {% endfor %}
                  </div>
               </div>

{#               <div class="widget widget_photostream">#}
{#                  <h5>Photostream</h5>#}
{#                  <ul class="photostream cf">#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                     <li><a href="#"><img src="images/thumb.jpg" alt="thumbnail"></a></li>#}
{#                  </ul>#}
{#	            </div>#}

            </aside>

         </div> <!-- Secondary End-->

      </div>

   </div> <!-- Content End-->

   <!-- Tweets Section
   ================================================== -->
{#   <section id="tweets">#}
{##}
{#      <div class="row">#}
{##}
{#         <div class="tweeter-icon align-center">#}
{#            <i class="fa fa-twitter"></i>#}
{#         </div>#}
{##}
{#         <ul id="twitter" class="align-center">#}
{#            <li>#}
{#               <span>#}
{#               This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.#}
{#               Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum#}
{#               <a href="#">http://t.co/CGIrdxIlI3</a>#}
{#               </span>#}
{#               <b><a href="#">2 Days Ago</a></b>#}
{#            </li>#}
{#            <!--#}
{#            <li>#}
{#               <span>#}
{#               This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.#}
{#               Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum#}
{#               <a href="#">http://t.co/CGIrdxIlI3</a>#}
{#               </span>#}
{#               <b><a href="#">3 Days Ago</a></b>#}
{#            </li>#}
{#            -->#}
{#         </ul>#}
{##}
{#         <p class="align-center"><a href="#" class="button">Follow us</a></p>#}
{##}
{#      </div>#}
{##}
{#   </section> <!-- Tweets Section End-->#}

    <!-- footer
   ================================================== -->
   <footer>

      <div class="row">

         <div class="twelve columns">

            <ul class="footer-nav">
					<li><a href="{% url 'blog:home' %}">Home</a></li>
              	<li><a href="{% url 'blog:index' %}">Blogs</a></li>
              	<li><a href="{% url 'blog:projects' %}">Projects</a></li>
              	<li><a href="{% url 'blog:about' %}">About</a></li>
{#              	<li><a href="#">Contact.</a></li>#}
{#               <li><a href="#">Features.</a></li>#}
			   </ul>

            <ul class="footer-social">
{#               <li><a href="#"><i class="fa fa-facebook"></i></a></li>#}
{#               <li><a href="#"><i class="fa fa-twitter"></i></a></li>#}
{#               <li><a href="#"><i class="fa fa-google-plus"></i></a></li>#}
               <li><a href="https://www.linkedin.com/in/%E8%88%AA-%E7%86%8A-9aa674156/"><i class="fa fa-linkedin"></i></a></li>
               <li><a href="https://www.facebook.com/hang.xiong.7758"><i class="fa fa-facebook"></i></a></li>
               <li><a href="https://www.instagram.com/teddy__xiong/"><i class="fa fa-instagram"></i></a></li>
               <li><a href="https://github.com/lifeNeedsCreation"><i class="fa fa-github"></i></a></li>
{#               <li><a href="#"><i class="fa fa-rss"></i></a></li>#}
            </ul>

<ul class="copyright">
               <li>&copy; Shu Liao</li>
{#               <li>Design by <a href="http://www.styleshout.com/">Styleshout</a></li>               #}
            </ul>

         </div>

         <div id="go-top" style="display: block;"><a title="Back to Top" href="#">Go To Top</a></div>

      </div>

   </footer> <!-- Footer End-->

   <!-- Java Script
   ================================================== -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script>window.jQuery || document.write('<script src="js/jquery-1.10.2.min.js"><\/script>')</script>
   <script type="text/javascript" src="{% static 'blog/js/jquery-migrate-1.2.1.min.js' %}"></script>

   <script src="{% static 'blog/js/jquery.flexslider.js' %}"></script>
   <script src="{% static 'blog/js/doubletaptogo.js' %}"></script>
   <script src="{% static 'blog/js/init.js' %}"></script>
   <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>

    {% block addtion_script %}
    {% endblock %}

</body>

</html>

blog/templates/blog/project_detail.html
{% extends 'blog/project_base.html' %}
{% load blog_tags %}
{% block pagetitle %}
<h1>{{ page_title }}</h1>
{% endblock %}

{% block leftpanel %}
    <h1>{{ proj.name }}</h1>

                  <div class="entry-description">

                     <p>{{ proj.intro }}</p>

                  </div>

                  <ul class="portfolio-meta-list">
						   <li><span>Date: </span>{{ proj.created_time }}</li>
{#						   <li><span>Client </span>Styleshout</li>#}
						   <li><span>Skills: </span>/ {% for tg in proj.skills.all %}{{ tg.name }} / {% endfor %}</li>
				      </ul>

                  <a class="button" href="{{ proj.link }}">View project</a>
{% endblock %}

{% block body %}

<div id="primary" class="eight columns">

               <div class="entry-media">

                  <img src="{{ proj.image }}" alt="" />

{#                  <img src="images/portfolio/entries/geometric-backgrounds-02.jpg" alt="" />#}

               </div>

               <div class="entry-excerpt">

				      {{ proj.body|safe }}

					</div>

            </div> <!-- primary end-->


{% endblock %}